#!/bin/bash
# Enables `claude --chrome` to work from WSL2 with Windows-installed Chrome
#
# Run this from inside your WSL2 distro. Idempotent — safe to re-run.
#
# What this does:
#   1. Symlinks Windows Chrome Extensions into WSL2 for extension detection
#   2. Creates a .bat bridge so Windows Chrome can call the WSL2 native host
#   3. Creates the Windows-side native messaging manifest
#   4. Sets the Windows registry key so Chrome finds the manifest
#   5. Ensures the Linux-side native host wrapper exists

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[x]${NC} $*"; exit 1; }

EXT_ID="fcoeoabgfenejglbffodgkkbkcdhcgfn"

# ── Pre-flight checks ──────────────────────────────────────────────

grep -qi microsoft /proc/version 2>/dev/null || error "This script must be run inside WSL"

WIN_USER=$(cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r') || error "Could not detect Windows username"
WIN_HOME="/mnt/c/Users/$WIN_USER"
[ -d "$WIN_HOME" ] || error "Windows home not found at $WIN_HOME"
info "Windows user: $WIN_USER"

WSL_DISTRO="${WSL_DISTRO_NAME:-}"
if [ -z "$WSL_DISTRO" ]; then
  WSL_DISTRO=$(wsl.exe -l -q 2>/dev/null | tr -d '\0\r' | head -1) || true
fi
[ -n "$WSL_DISTRO" ] || error "Could not detect WSL distro name. Set WSL_DISTRO_NAME env var."
info "WSL distro: $WSL_DISTRO"

# Use the stable symlink path so the bridge survives Claude Code updates
CLAUDE_BIN=$(which claude 2>/dev/null) || error "claude not found in PATH. Install Claude Code in WSL first."
info "Claude binary: $CLAUDE_BIN"

CHROME_DATA="$WIN_HOME/AppData/Local/Google/Chrome/User Data"
[ -d "$CHROME_DATA" ] || error "Windows Chrome not found at $CHROME_DATA"

# Find which Chrome profile has the extension
EXT_FOUND=false
PROFILE_NAME=""
for profile_dir in "$CHROME_DATA"/Default "$CHROME_DATA"/Profile\ *; do
  [ -d "$profile_dir" ] || continue
  if [ -d "$profile_dir/Extensions/$EXT_ID" ]; then
    PROFILE_NAME=$(basename "$profile_dir")
    info "Claude in Chrome extension found in profile: $PROFILE_NAME"
    EXT_FOUND=true
    break
  fi
done
if ! $EXT_FOUND; then
  error "Claude in Chrome extension not found in any Chrome profile.\n  Install it from: https://chromewebstore.google.com/detail/claude/fcoeoabgfenejglbffodgkkbkcdhcgfn"
fi

# ── Step 1: Extension detection symlink ─────────────────────────────

info "Setting up extension detection..."

LINUX_CHROME_DIR="$HOME/.config/google-chrome"
LINUX_PROFILE_DIR="$LINUX_CHROME_DIR/$PROFILE_NAME"
LINUX_EXT_LINK="$LINUX_PROFILE_DIR/Extensions"
WIN_EXT_DIR="$profile_dir/Extensions"

# Create real directory (Node's readdir needs a real dir, not a symlink to a dir)
if [ -L "$LINUX_PROFILE_DIR" ]; then
  rm "$LINUX_PROFILE_DIR"
fi
mkdir -p "$LINUX_PROFILE_DIR"

# Symlink Extensions inside the real directory
if [ -L "$LINUX_EXT_LINK" ]; then
  CURRENT_TARGET=$(readlink "$LINUX_EXT_LINK")
  if [ "$CURRENT_TARGET" = "$WIN_EXT_DIR" ]; then
    info "Extensions symlink already correct"
  else
    warn "Updating Extensions symlink (was: $CURRENT_TARGET)"
    rm "$LINUX_EXT_LINK"
    ln -s "$WIN_EXT_DIR" "$LINUX_EXT_LINK"
  fi
elif [ -d "$LINUX_EXT_LINK" ]; then
  warn "Extensions is a real directory, replacing with symlink"
  rmdir "$LINUX_EXT_LINK" 2>/dev/null || error "Cannot replace $LINUX_EXT_LINK — not empty"
  ln -s "$WIN_EXT_DIR" "$LINUX_EXT_LINK"
else
  ln -s "$WIN_EXT_DIR" "$LINUX_EXT_LINK"
fi
info "Extension detection: $LINUX_EXT_LINK -> $WIN_EXT_DIR"

# ── Step 2: Windows-side .bat bridge ────────────────────────────────

info "Setting up native host bridge..."

WIN_CLAUDE_CHROME="$WIN_HOME/.claude/chrome"
BAT_FILE="$WIN_CLAUDE_CHROME/chrome-native-host.bat"

mkdir -p "$WIN_CLAUDE_CHROME"

if [ -f "$BAT_FILE" ] && grep -q "wsl.exe" "$BAT_FILE" 2>/dev/null; then
  info "Native host .bat already bridges to WSL"
else
  if [ -f "$BAT_FILE" ]; then
    cp "$BAT_FILE" "${BAT_FILE}.bak"
    info "Backed up existing .bat to ${BAT_FILE}.bak"
  fi

  cat > "$BAT_FILE" << BATEOF
@echo off
REM Chrome native host bridge: Windows Chrome -> WSL2 Claude Code
REM Generated by setup-wsl-chrome-bridge.sh — re-run script to regenerate
wsl.exe -d ${WSL_DISTRO} -- ${CLAUDE_BIN} --chrome-native-host
BATEOF
  info "Created $BAT_FILE"
fi

# ── Step 3: Windows-side native messaging manifest ──────────────────

info "Setting up native messaging manifest..."

# Convert WSL path to Windows path for the manifest
MANIFEST_FILE="$WIN_CLAUDE_CHROME/com.anthropic.claude_code_browser_extension.json"

# Note: JSON requires escaped backslashes (\\) in paths
cat > "$MANIFEST_FILE" <<EOF
{
  "name": "com.anthropic.claude_code_browser_extension",
  "description": "Claude Code Browser Extension Native Host (WSL2 bridge)",
  "path": "C:\\\\Users\\\\${WIN_USER}\\\\.claude\\\\chrome\\\\chrome-native-host.bat",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://${EXT_ID}/"
  ]
}
EOF
info "Manifest: $MANIFEST_FILE"

# ── Step 4: Windows registry key ────────────────────────────────────

info "Setting up Windows registry..."

REG_KEY="HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts\\com.anthropic.claude_code_browser_extension"
WIN_MANIFEST_PATH="C:\\Users\\${WIN_USER}\\.claude\\chrome\\com.anthropic.claude_code_browser_extension.json"

# Check current registry state
REG_VALUE=$(reg.exe query "$REG_KEY" /ve 2>/dev/null | tr -d '\r' | grep REG_SZ | awk '{print $NF}') || true

if [ "$REG_VALUE" = "$WIN_MANIFEST_PATH" ]; then
  info "Registry key already correct"
else
  reg.exe add "$REG_KEY" /ve /t REG_SZ /d "$WIN_MANIFEST_PATH" /f >/dev/null 2>&1 \
    || error "Failed to set registry key. Try running from an elevated terminal."
  info "Registry key set: $REG_KEY -> $WIN_MANIFEST_PATH"
fi

# ── Step 5: Linux-side native host wrapper ──────────────────────────

info "Checking Linux-side native host..."

NATIVE_HOST="$HOME/.claude/chrome/chrome-native-host"

if [ -f "$NATIVE_HOST" ]; then
  info "Linux native host wrapper already exists"
else
  mkdir -p "$(dirname "$NATIVE_HOST")"
  cat > "$NATIVE_HOST" << SHEOF
#!/bin/sh
# Chrome native host wrapper script
# Generated by setup-wsl-chrome-bridge.sh
exec "$CLAUDE_BIN" --chrome-native-host
SHEOF
  chmod +x "$NATIVE_HOST"
  info "Created $NATIVE_HOST"
fi

# ── Done ────────────────────────────────────────────────────────────

echo ""
info "Setup complete!"
echo ""
echo "  Next steps:"
echo "  1. Close and reopen Chrome (to pick up the new native messaging host)"
echo "  2. Start Claude Code with: claude --chrome"
echo ""
warn "If Claude Code updates overwrite the .bat file, re-run this script."